# 02_map_crs_features.R
#
# Map CRS Ensembl features to HGNC gene symbols.
#
# Run from an analysis workspace configured through environment variables.

options(stringsAsFactors = FALSE)
options(timeout = 1800)


# Analysis paths are supplied through environment variables.
required_env_path <- function(name) {
  value <- Sys.getenv(name, unset = "")
  if (!nzchar(value)) {
    stop("Environment variable ", name, " is not set.")
  }
  normalizePath(value, winslash = "/", mustWork = TRUE)
}

project_dir <- required_env_path("RADIOGENOMICS_PROJECT_DIR")
setwd(project_dir)

if (!requireNamespace("openxlsx", quietly = TRUE)) {
  stop("Missing R package 'openxlsx'. Install dependencies with environment/install_r_dependencies.R.")
}

library(openxlsx)

dirs <- c(
  "01_raw_data/GeneAnnotation",
  "02_metadata",
  "05_molecular_scores",
  "06_models",
  "07_results"
)

for (d in dirs) {
  dir.create(d, recursive = TRUE, showWarnings = FALSE)
}

cat("\n===== Current working directory =====\n")
print(getwd())

############################################################
# 1. Check HGNC annotation file
############################################################

hgnc_path <- "01_raw_data/GeneAnnotation/hgnc_complete_set.txt"

cat("\n===== Checking HGNC annotation file =====\n")
cat("Expected path:\n")
cat(hgnc_path, "\n")

if (!file.exists(hgnc_path)) {
  stop(
    "The HGNC annotation file hgnc_complete_set.txt was not found.\n\n",
    "Download hgnc_complete_set.txt and place it at the expected path.\n",
    "Expected path: 01_raw_data/GeneAnnotation/hgnc_complete_set.txt\n"
  )
}

cat("HGNC annotation file found.\n")
print(file.info(hgnc_path))

############################################################
# 2. Load patient expression matrix from the transcriptome audit
############################################################

patient_expr_path <- "01_raw_data/NSCLC_Radiogenomics/GSE103584_NSCLC_RNAseq_SYMBOL_gene_by_sample_RAW_AUDITED.rds"

if (!file.exists(patient_expr_path)) {
  stop(
    "The patient expression matrix generated by the preceding step was not found:\n",
    patient_expr_path,
    "\nRun the transcriptome audit step first."
  )
}

patient_expr <- readRDS(patient_expr_path)
patient_symbols <- rownames(patient_expr)

cat("\n===== Patient expression loaded =====\n")
cat("Patient expression dim, genes x samples:\n")
print(dim(patient_expr))

cat("\nPatient gene symbol preview:\n")
print(head(patient_symbols, 30))

############################################################
# 3. Load CRS model
############################################################

crs_model_path <- "06_models/crs_elastic_net_model.rds"

if (!file.exists(crs_model_path)) {
  stop(
    "The trained CRS model was not found:\n",
    crs_model_path
  )
}

crs_model_obj <- readRDS(crs_model_path)
final_features <- crs_model_obj$final_features

cat("\n===== CRS model loaded =====\n")
cat("CRS final selected features:\n")
print(length(final_features))

cat("\nCRS gene ID type:\n")
print(crs_model_obj$gene_id_type)

coef_mat <- as.matrix(
  coef(
    crs_model_obj$final_model$fit,
    s = "lambda.min"
  )
)

coef_df <- data.frame(
  ensembl = rownames(coef_mat),
  coefficient = as.numeric(coef_mat[, 1]),
  stringsAsFactors = FALSE
)

intercept_value <- coef_df$coefficient[coef_df$ensembl == "(Intercept)"]

coef_nonzero <- coef_df[
  coef_df$coefficient != 0 & coef_df$ensembl != "(Intercept)",
]

nonzero_features <- coef_nonzero$ensembl

cat("\nNumber of non-zero CRS coefficients:\n")
print(length(nonzero_features))

cat("\nCRS intercept:\n")
print(intercept_value)

############################################################
# 4. Read HGNC annotation table
############################################################

cat("\n===== Reading HGNC complete set =====\n")

hgnc <- read.delim(
  hgnc_path,
  header = TRUE,
  sep = "\t",
  check.names = FALSE,
  stringsAsFactors = FALSE,
  quote = "",
  comment.char = ""
)

cat("\nHGNC table dim:\n")
print(dim(hgnc))

cat("\nHGNC columns preview:\n")
print(head(colnames(hgnc), 50))

required_cols <- c("symbol", "ensembl_gene_id")

if (!all(required_cols %in% colnames(hgnc))) {
  stop(
    "The HGNC file does not contain symbol and ensembl_gene_id columns.\n",
    "Inspect the HGNC column names and update the parser if necessary."
  )
}

clean_ensembl <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x <- sub("\\..*$", "", x)
  return(x)
}

clean_symbol <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x <- toupper(x)
  return(x)
}

hgnc_map <- data.frame(
  ensembl = clean_ensembl(hgnc$ensembl_gene_id),
  symbol = clean_symbol(hgnc$symbol),
  hgnc_id = if ("hgnc_id" %in% colnames(hgnc)) hgnc$hgnc_id else NA,
  name = if ("name" %in% colnames(hgnc)) hgnc$name else NA,
  locus_group = if ("locus_group" %in% colnames(hgnc)) hgnc$locus_group else NA,
  locus_type = if ("locus_type" %in% colnames(hgnc)) hgnc$locus_type else NA,
  stringsAsFactors = FALSE
)

hgnc_map <- hgnc_map[
  !is.na(hgnc_map$ensembl) &
    hgnc_map$ensembl != "" &
    !is.na(hgnc_map$symbol) &
    hgnc_map$symbol != "",
]

hgnc_map <- unique(hgnc_map)

cat("\nClean HGNC Ensembl-Symbol mapping dim:\n")
print(dim(hgnc_map))

cat("\nHGNC mapping preview:\n")
print(head(hgnc_map, 20))

############################################################
# 5. Map CRS final features and non-zero features
############################################################

crs_feature_table <- data.frame(
  ensembl = final_features,
  stringsAsFactors = FALSE
)

crs_feature_map <- merge(
  crs_feature_table,
  hgnc_map,
  by = "ensembl",
  all.x = TRUE,
  sort = FALSE
)

crs_feature_map$symbol_in_patient <- crs_feature_map$symbol %in% patient_symbols

coef_nonzero_map <- merge(
  coef_nonzero,
  hgnc_map,
  by = "ensembl",
  all.x = TRUE,
  sort = FALSE
)

coef_nonzero_map$symbol_in_patient <- coef_nonzero_map$symbol %in% patient_symbols

############################################################
# 6. Aggregate duplicated symbols if needed
############################################################

coef_available <- coef_nonzero_map[
  !is.na(coef_nonzero_map$symbol) &
    coef_nonzero_map$symbol != "" &
    coef_nonzero_map$symbol_in_patient,
]

# If multiple Ensembl IDs map to same symbol, sum coefficients.
coef_symbol <- aggregate(
  coefficient ~ symbol,
  data = coef_available,
  FUN = sum
)

coef_symbol <- coef_symbol[order(abs(coef_symbol$coefficient), decreasing = TRUE), ]

############################################################
# 7. Mapping summaries
############################################################

mapping_summary <- data.frame(
  item = c(
    "CRS_final_features_total",
    "CRS_final_features_mapped_to_symbol",
    "CRS_final_features_present_in_patient",
    "CRS_final_feature_patient_overlap_fraction",
    "CRS_nonzero_features_total",
    "CRS_nonzero_features_mapped_to_symbol",
    "CRS_nonzero_features_present_in_patient",
    "CRS_nonzero_feature_patient_overlap_fraction",
    "Unique_patient_symbols_used_for_CRS",
    "CRS_intercept"
  ),
  value = c(
    length(final_features),
    sum(!is.na(crs_feature_map$symbol) & crs_feature_map$symbol != ""),
    sum(crs_feature_map$symbol_in_patient, na.rm = TRUE),
    round(sum(crs_feature_map$symbol_in_patient, na.rm = TRUE) / length(final_features), 4),
    length(nonzero_features),
    sum(!is.na(coef_nonzero_map$symbol) & coef_nonzero_map$symbol != ""),
    sum(coef_nonzero_map$symbol_in_patient, na.rm = TRUE),
    round(sum(coef_nonzero_map$symbol_in_patient, na.rm = TRUE) / length(nonzero_features), 4),
    nrow(coef_symbol),
    intercept_value
  ),
  stringsAsFactors = FALSE
)

cat("\n===== CRS Ensembl-to-Symbol mapping summary =====\n")
print(mapping_summary)

cat("\n===== Non-zero CRS coefficient mapping preview =====\n")
print(head(coef_nonzero_map, 50))

cat("\n===== Patient-available CRS symbol coefficients preview =====\n")
print(head(coef_symbol, 50))

missing_nonzero <- coef_nonzero_map[
  is.na(coef_nonzero_map$symbol) |
    coef_nonzero_map$symbol == "" |
    !coef_nonzero_map$symbol_in_patient,
]

cat("\n===== Missing non-zero CRS features after HGNC mapping preview =====\n")
print(head(missing_nonzero, 50))

############################################################
# 8. Decision flag
############################################################

nonzero_overlap_fraction <- sum(coef_nonzero_map$symbol_in_patient, na.rm = TRUE) /
  length(nonzero_features)

decision <- ifelse(
  nonzero_overlap_fraction >= 0.80,
  "PASS: CRS can be approximately transferred to GSE103584 using HGNC Gene Symbols",
  "WARNING: Non-zero CRS feature overlap is low; CRS transfer needs caution"
)

cat("\n===== Mapping decision =====\n")
print(decision)

############################################################
# 9. Save outputs
############################################################

wb <- createWorkbook()

addWorksheet(wb, "HGNC_mapping_preview")
writeData(wb, "HGNC_mapping_preview", head(hgnc_map, 1000))

addWorksheet(wb, "CRS_all_feature_map")
writeData(wb, "CRS_all_feature_map", crs_feature_map)

addWorksheet(wb, "CRS_nonzero_feature_map")
writeData(wb, "CRS_nonzero_feature_map", coef_nonzero_map)

addWorksheet(wb, "CRS_symbol_coefficients")
writeData(wb, "CRS_symbol_coefficients", coef_symbol)

addWorksheet(wb, "mapping_summary")
writeData(wb, "mapping_summary", mapping_summary)

addWorksheet(wb, "missing_nonzero_features")
writeData(wb, "missing_nonzero_features", missing_nonzero)

addWorksheet(wb, "decision")
writeData(wb, "decision", data.frame(decision = decision))

saveWorkbook(
  wb,
  file = "02_metadata/crs_feature_mapping_summary.xlsx",
  overwrite = TRUE
)

saveRDS(
  hgnc_map,
  file = "02_metadata/hgnc_ensembl_symbol_mapping.rds"
)

saveRDS(
  crs_feature_map,
  file = "02_metadata/crs_all_feature_mapping.rds"
)

saveRDS(
  coef_nonzero_map,
  file = "02_metadata/crs_nonzero_feature_mapping.rds"
)

saveRDS(
  list(
    intercept = intercept_value,
    symbol_coefficients = coef_symbol,
    nonzero_feature_map = coef_nonzero_map,
    decision = decision,
    note = "Coefficients are aggregated by Gene Symbol when multiple Ensembl features map to the same symbol."
  ),
  file = "06_models/crs_gene_symbol_coefficients.rds"
)

cat("\n===== CRS gene-symbol mapping audit completed =====\n")
cat("Main output files:\n")
cat("1. 02_metadata/crs_feature_mapping_summary.xlsx\n")
cat("2. 06_models/crs_gene_symbol_coefficients.rds\n")

cat("1. HGNC table dim\n")
cat("2. CRS Ensembl-to-Symbol mapping summary\n")
cat("3. Patient-available CRS symbol coefficients preview\n")
cat("4. Missing non-zero CRS features after HGNC mapping preview\n")
cat("5. Mapping decision\n")
